export const techSkills = [
  { skillName: "HTML", img: "./assets/html.png" },
  { skillName: "CSS", img: "./assets/css.png" },
  { skillName: "Javascript", img: "./assets/JavaScript-logo.png" },
  { skillName: "JQuery", img: "./assets/jquery.png" },
  { skillName: "Typescript", img: "./assets/typescript.png" },
  { skillName: "React", img: "./assets/react.svg" },
  { skillName: "Boostrap", img: "./assets/bootstrap.jpg" },
  { skillName: "MUI", img: "./assets/MUI.png" },
  { skillName: "Tailwind", img: "./assets/tailwind.png" },
  { skillName: "Express", img: "./assets/ExpressJs.png" },
  { skillName: "NodeJS", img: "./assets/nodejs.png" },
  { skillName: "Git", img: "./assets/git-logo.png" },
  { skillName: "PostgreSQL", img: "./assets/postgres.png" },
  { skillName: "MongoDB", img: "./assets/mongo.png" },
  { skillName: "Figma", img: "./assets/figma.png" },
  { skillName: "Photoshop", img: "./assets/ps.png" },
  { skillName: "InDesign", img: "./assets/indesign.png" },
  { skillName: "Autodesk 3DMax", img: "./assets/3ds-max.png" },
  { skillName: "Autodesk Autocad", img: "./assets/autocad.png" },
  { skillName: "Autodesk Revit", img: "./assets/revit.png" },
  { skillName: "Google SketchUp", img: "./assets/su.jpg" },
  { skillName: "Lumion", img: "./assets/lumion.png" },
];
export const designSkills = [];
export default { techSkills, designSkills };
